services:
  db:
    image: postgres:latest
    container_name: restapi
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - '${PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local